### ISSUE TITLE
check-tomcat-app-deployment.rb: password misspelled in: long: '--passowrd PASSWORD',

### ISSUE THREAD

**Issue by luyseyal** [smbambling/sensu-plugins-tomcat#2]
Password is misspelled in check-tomcat-app-deployment.rb
`long: '--passowrd PASSWORD'`

**Comment by smbambling** [comment]
Sorry I need to update the README stating that I have actually released this plugin to the sensu-plugins team to allow for better community support.  You can see it here https://github.com/sensu-plugins/sensu-plugins-tomcat

The bug you listed has been corrected and a new version of the GEM has already been released.

Thanks so much for  helping improve this project !
